# Generated by Django 3.1.1 on 2021-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(default='-', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
