# Generated by Django 3.1.1 on 2021-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_people_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='-', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
